// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMessageQueue.DAL;

namespace MyMessageQueue.DAL.Migrations
{
    [DbContext(typeof(MyMessageQueueDBContext))]
    [Migration("20210223142738_errorLog")]
    partial class errorLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyMessageQueue.Model.LogMessage", b =>
                {
                    b.Property<int>("LogMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("LogMessageId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("MyMessageQueue.Model.QueueMessage", b =>
                {
                    b.Property<int>("QueueMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ErrorRequeuedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequedCount")
                        .HasColumnType("int");

                    b.HasKey("QueueMessageId");

                    b.ToTable("MyMessageQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
